apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front-con
        image: oolralra/front:1
---
apiVersion: v1
kind: Service
metadata:
  name: svc-front
spec:
  selector:
    app: front
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
